services:
  magic-mirror:
    container_name: magic-mirror
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    command: ["node", "--run", "server"]
    ports:
      - "8081:8081"
    volumes:
      - ./config:/opt/magic_mirror/config:rw
      - ./modules/MMM-Dad-Jokes:/opt/magic_mirror/modules/MMM-Dad-Jokes
      - ./modules/MMM-SolarPicture:/opt/magic_mirror/modules/MMM-SolarPicture
      - ./modules/MMM-PreciousMetals:/opt/magic_mirror/modules/MMM-PreciousMetals
    environment:
      MM_SCENARIO: server
      MM_OVERRIDE_DEFAULT_MODULES: "true"
    networks:
      - fortress-phronesis-net

networks:
  fortress-phronesis-net:
    external: true
    name: fortress-phronesis-net
