services:
  magic-mirror:
    container_name: magic-mirror
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    command: ["node", "--run", "server"]
    user: "0"
    ports:
      - "8081:8081"
    volumes:
      - ./config:/opt/magic_mirror/config:rw
      - ./modules/MMM-Dad-Jokes:/opt/magic_mirror/modules/MMM-Dad-Jokes
      - ./modules/MMM-SolarPicture:/opt/magic_mirror/modules/MMM-SolarPicture
      - ./modules/MMM-PreciousMetals:/opt/magic_mirror/modules/MMM-PreciousMetals
      - ./modules/MMM-Pollen:/opt/magic_mirror/modules/MMM-Pollen
      - ./modules/MMM-GooglePhotos:/opt/magic_mirror/modules/MMM-GooglePhotos
      - ./modules/MMM-EasyPix:/opt/magic_mirror/modules/MMM-EasyPix
      - ${HOME}/Pictures/GalleryDen2:/opt/magic_mirror/external_pics/GalleryDen2:ro
      - ./modules/Solomon-Cal-Magic-Mirror/MMM-SolomonicPrayerClock:/opt/magic_mirror/modules/MMM-SolomonicPrayerClock
    environment:
      MM_SCENARIO: server
      MM_OVERRIDE_DEFAULT_MODULES: "true"
    networks:
      - fortress-phronesis-net

networks:
  fortress-phronesis-net:
    external: true
    name: fortress-phronesis-net
